apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-crm.fullname" . }}-conf
  labels:
    {{- include "demo-crm.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  PERSISTENCE: {{ .Values.config.persistence | quote }}
